version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-222-30-53.compute-1.amazonaws.com
            port: '5432'
            database: dd7s3jnr3jqc70
            ssl: true
            user: jbgqaofsndetxg
            password: 5acd31a9997e32f24501b84e6c7d4aba8376c2ca35e72e9394af90b84287b1d6
            migrations: true
